"""Tests for the Databricks SQL generator."""

from __future__ import annotations

import pytest

from a2d.config import ConversionConfig
from a2d.generators.sql import SQLGenerator
from a2d.ir.graph import WorkflowDAG
from a2d.ir.nodes import (
    AggAction,
    AggregationField,
    FilterNode,
    JoinKey,
    JoinNode,
    ReadNode,
    SortField,
    SortNode,
    SummarizeNode,
)


@pytest.fixture
def config() -> ConversionConfig:
    return ConversionConfig()


@pytest.fixture
def generator(config: ConversionConfig) -> SQLGenerator:
    return SQLGenerator(config)


class TestSQLReadNode:
    def test_read_csv_generates_cte(self, generator: SQLGenerator):
        """ReadNode produces a CTE selecting from the CSV path."""
        node = ReadNode(
            node_id=1,
            original_tool_type="Input Data",
            file_path="/data/input.csv",
            file_format="csv",
        )
        dag = WorkflowDAG()
        dag.add_node(node)

        output = generator.generate(dag, "test_sql")
        content = output.files[0].content

        assert output.files[0].filename == "test_sql.sql"
        assert output.files[0].file_type == "sql"
        assert "WITH" in content
        assert "csv.`/data/input.csv`" in content
        assert "SELECT * FROM" in content


class TestSQLFilterNode:
    def test_filter_generates_where_clause(self, generator: SQLGenerator):
        """FilterNode produces a CTE with a WHERE clause."""
        read = ReadNode(node_id=1, original_tool_type="Input Data", file_path="/data.csv", file_format="csv")
        filt = FilterNode(node_id=2, original_tool_type="Filter", expression="[Age] > 25")

        dag = WorkflowDAG()
        dag.add_node(read)
        dag.add_node(filt)
        dag.add_edge(1, 2)

        output = generator.generate(dag)
        content = output.files[0].content

        assert "WHERE" in content
        assert "step_2_filter" in content


class TestSQLJoinNode:
    def test_join_generates_join_clause(self, generator: SQLGenerator):
        """JoinNode produces a CTE with a JOIN ON clause."""
        left = ReadNode(node_id=1, original_tool_type="Input Data", file_path="/left.csv", file_format="csv")
        right = ReadNode(node_id=2, original_tool_type="Input Data", file_path="/right.csv", file_format="csv")
        join = JoinNode(
            node_id=3,
            original_tool_type="Join",
            join_keys=[JoinKey(left_field="id", right_field="id")],
            join_type="inner",
        )

        dag = WorkflowDAG()
        dag.add_node(left)
        dag.add_node(right)
        dag.add_node(join)
        dag.add_edge(1, 3, destination_anchor="Left")
        dag.add_edge(2, 3, destination_anchor="Right")

        output = generator.generate(dag)
        content = output.files[0].content

        assert "JOIN" in content
        assert "ON" in content
        assert "`id`" in content


class TestSQLSummarize:
    def test_summarize_generates_group_by(self, generator: SQLGenerator):
        """SummarizeNode produces GROUP BY SQL."""
        read = ReadNode(node_id=1, original_tool_type="Input Data", file_path="/data.csv", file_format="csv")
        summ = SummarizeNode(
            node_id=2,
            original_tool_type="Summarize",
            aggregations=[
                AggregationField(field_name="Dept", action=AggAction.GROUP_BY),
                AggregationField(field_name="Salary", action=AggAction.SUM, output_field_name="Total"),
            ],
        )

        dag = WorkflowDAG()
        dag.add_node(read)
        dag.add_node(summ)
        dag.add_edge(1, 2)

        output = generator.generate(dag)
        content = output.files[0].content

        assert "GROUP BY" in content
        assert "SUM(" in content
        assert "`Total`" in content
        assert "`Dept`" in content


class TestSQLFormat:
    def test_sql_header_and_structure(self, generator: SQLGenerator):
        """SQL output should have migration header, WITH clause, and final SELECT."""
        read = ReadNode(node_id=1, original_tool_type="Input Data", file_path="/data.csv", file_format="csv")
        dag = WorkflowDAG()
        dag.add_node(read)

        output = generator.generate(dag, "my_workflow")
        content = output.files[0].content

        assert "-- Migrated from: my_workflow.yxmd" in content
        assert "-- Generated by: a2d v0.1.0" in content
        assert "WITH" in content
        assert content.strip().endswith(";")

    def test_sort_generates_order_by(self, generator: SQLGenerator):
        """SortNode produces ORDER BY SQL."""
        read = ReadNode(node_id=1, original_tool_type="Input Data", file_path="/data.csv", file_format="csv")
        sort = SortNode(
            node_id=2,
            original_tool_type="Sort",
            sort_fields=[
                SortField(field_name="Name", ascending=True),
                SortField(field_name="Age", ascending=False),
            ],
        )

        dag = WorkflowDAG()
        dag.add_node(read)
        dag.add_node(sort)
        dag.add_edge(1, 2)

        output = generator.generate(dag)
        content = output.files[0].content

        assert "ORDER BY" in content
        assert "`Name` ASC" in content
        assert "`Age` DESC" in content
