"""Abstract base class for all code generators.

Each concrete generator walks a :class:`~a2d.ir.graph.WorkflowDAG` and
produces one or more output files (PySpark notebooks, SQL scripts, JSON
workflow definitions, etc.).
"""

from __future__ import annotations

import ast
import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field

from a2d.config import ConversionConfig
from a2d.ir.graph import WorkflowDAG

logger = logging.getLogger("a2d.generators.base")


@dataclass
class GeneratedFile:
    """A single generated output file."""

    filename: str
    content: str
    file_type: str  # "python", "sql", "json"


@dataclass
class GeneratedOutput:
    """Collection of generated files plus metadata."""

    files: list[GeneratedFile] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    stats: dict = field(default_factory=dict)


@dataclass
class NodeCodeResult:
    """Result of generating code for a single IR node."""

    code_lines: list[str] = field(default_factory=list)
    output_vars: dict[str, str] = field(default_factory=dict)
    imports: set[str] = field(default_factory=set)
    warnings: list[str] = field(default_factory=list)


# Shared file format mapping (superset of all generators)
_FILE_FORMAT_MAP: dict[str, str] = {
    "csv": "csv",
    "xlsx": "com.crealytics.spark.excel",
    "xls": "com.crealytics.spark.excel",
    "yxdb": "parquet",  # yxdb -> parquet as best approximation
    "json": "json",
    "parquet": "parquet",
    "avro": "avro",
    "sas7bdat": "com.github.saurfang.sas.spark",
    "dbf": "com.github.saurfang.spark.dbf",
    "": "csv",  # default
}


class CodeGenerator(ABC):
    """Abstract base for code generators."""

    def __init__(self, config: ConversionConfig) -> None:
        self.config = config
        self.metadata: dict[str, object] = {}

    @abstractmethod
    def generate(self, dag: WorkflowDAG, workflow_name: str = "workflow") -> GeneratedOutput:
        """Walk the DAG and produce generated files."""
        ...

    def _build_header_lines(self, workflow_name: str, comment_prefix: str = "#") -> list[str]:
        """Build a standard header from metadata (coverage, confidence, version)."""
        from a2d.__about__ import __version__

        lines = [
            f"{comment_prefix} Migrated from: {workflow_name}.yxmd",
            f"{comment_prefix} Generated by: a2d v{__version__}",
        ]

        stats = self.metadata.get("stats")
        if isinstance(stats, dict):
            total = stats.get("total_nodes", 0)
            supported = stats.get("supported_nodes", 0)
            pct = f"{supported}/{total} nodes ({supported / total * 100:.0f}%)" if total else "N/A"
            lines.append(f"{comment_prefix} Coverage: {pct}")

        confidence = self.metadata.get("confidence")
        if confidence is not None:
            overall = getattr(confidence, "overall", None)
            level = getattr(confidence, "level", None)
            if overall is not None and level is not None:
                lines.append(f"{comment_prefix} Confidence: {level} ({overall:.0f}/100)")

        lines.append(f"{comment_prefix}")
        lines.append(f'{comment_prefix} Search for "TODO" and "WARNING" for items requiring manual review.')
        return lines

    def _build_footer_lines(self, code: str, comment_prefix: str = "#") -> list[str]:
        """Build a 'next steps' footer comment with dynamic TODO/WARNING counts."""
        todo_count = code.count("# TODO") + code.count("-- TODO")
        warn_count = code.count("# WARNING") + code.count("-- WARNING")

        lines = [
            "",
            f"{comment_prefix} -- Next steps --",
        ]
        step = 1
        if todo_count > 0:
            lines.append(
                f'{comment_prefix} {step}. Search for "TODO" — {todo_count} item{"s" if todo_count != 1 else ""} need{"" if todo_count != 1 else "s"} manual attention'
            )
            step += 1
        if warn_count > 0:
            lines.append(
                f'{comment_prefix} {step}. Search for "WARNING" — {warn_count} item{"s" if warn_count != 1 else ""} flagged for review'
            )
            step += 1
        lines.append(f"{comment_prefix} {step}. Update database connections to Unity Catalog references")
        step += 1
        lines.append(f"{comment_prefix} {step}. Run: a2d validate <output_file>")
        return lines

    @staticmethod
    def _get_single_input(input_vars: dict[str, str]) -> str:
        """Return the single input variable name (most common case)."""
        if "Input" in input_vars:
            return input_vars["Input"]
        if input_vars:
            return next(iter(input_vars.values()))
        return "MISSING_INPUT"

    @staticmethod
    def _map_file_format(fmt: str) -> str:
        """Map Alteryx file format strings to Spark format names."""
        return _FILE_FORMAT_MAP.get(fmt.lower(), fmt.lower()) if fmt else "csv"

    @staticmethod
    def _validate_python_syntax(code: str, filename: str = "<generated>") -> list[str]:
        """Validate generated Python code with ast.parse().

        Returns a list of syntax error descriptions (empty if valid).
        """
        # Strip Databricks notebook magic lines (# Databricks notebook source, # COMMAND ----)
        # and magic commands (%sql, %md, etc.) which are not valid Python
        lines = []
        for line in code.splitlines():
            stripped = line.strip()
            if stripped.startswith("# Databricks notebook source"):
                continue
            if stripped.startswith("# COMMAND"):
                continue
            if stripped.startswith("%"):
                lines.append(f"# {line}")  # comment out magic commands
                continue
            lines.append(line)

        cleaned = "\n".join(lines)
        try:
            ast.parse(cleaned, filename=filename)
            return []
        except SyntaxError as e:
            msg = f"Syntax error in {filename}: {e.msg} (line {e.lineno})"
            logger.warning(msg)
            return [msg]
