"""Databricks Asset Bundle (DAB) generator.

Generates a complete DAB project structure:
  databricks.yml
  resources/<name>_job.yml
  src/<name>.py
  environments/{dev,staging,prod}.yml
"""

from __future__ import annotations

import logging

from a2d.config import ConversionConfig
from a2d.generators.base import GeneratedFile, GeneratedOutput
from a2d.ir.graph import WorkflowDAG

logger = logging.getLogger("a2d.generators.dab")


class DABGenerator:
    """Generate Databricks Asset Bundle project files."""

    def __init__(self, config: ConversionConfig) -> None:
        self.config = config

    def generate(self, dag: WorkflowDAG, workflow_name: str, output: GeneratedOutput) -> list[GeneratedFile]:
        """Generate DAB project files."""
        files: list[GeneratedFile] = []

        # 1. Main databricks.yml
        files.append(self._generate_databricks_yml(workflow_name))

        # 2. Job resource definition
        files.append(self._generate_job_yml(workflow_name))

        # 3. Source file (copy the main generated code)
        main_code = self._find_main_code(output)
        if main_code:
            files.append(
                GeneratedFile(
                    filename=f"src/{workflow_name}.py",
                    content=main_code,
                    file_type="python",
                )
            )

        # 4. Environment configs
        for env in ("dev", "staging", "prod"):
            files.append(self._generate_env_yml(workflow_name, env))

        return files

    def _generate_databricks_yml(self, workflow_name: str) -> GeneratedFile:
        """Generate the main databricks.yml bundle config."""
        content = f"""# Databricks Asset Bundle configuration
# Generated by a2d — review and customize before deployment

bundle:
  name: {workflow_name}_migration

include:
  - resources/*.yml
  - environments/*.yml

workspace:
  root_path: /Workspace/Users/${{workspace.current_user.userName}}/{workflow_name}
"""
        return GeneratedFile(
            filename="databricks.yml",
            content=content,
            file_type="yaml",
        )

    def _generate_job_yml(self, workflow_name: str) -> GeneratedFile:
        """Generate the job resource YAML.

        Uses ``job_clusters[]`` + ``job_cluster_key: main`` indirection rather
        than an inline ``new_cluster`` per task. This matches Databricks best
        practice and aligns with the Workflow JSON generator: callers can swap
        the cluster spec in one place and every task picks it up.

        ``node_type_id`` is selected from
        :data:`a2d.config.CLOUD_NODE_TYPE_IDS` based on
        ``ConversionConfig.cloud`` so the produced bundle works on the user's
        actual workspace cloud.
        """
        catalog = self.config.catalog_name
        schema = self.config.schema_name
        # Cloud-aware worker SKU. Defaults to AWS (i3.xlarge); override via
        # `--cloud azure` (Standard_DS3_v2) or `--cloud gcp` (n1-highmem-4).
        node_type_id = self.config.node_type_id

        content = f"""# Job definition for {workflow_name}
# Generated by a2d — review and customize before deployment

resources:
  jobs:
    {workflow_name}_job:
      name: "{workflow_name}"
      schedule:
        quartz_cron_expression: "0 0 8 * * ?"
        timezone_id: "UTC"

      job_clusters:
        - job_cluster_key: "main"
          new_cluster:
            spark_version: "{self.config.spark_version}"
            num_workers: 2
            # Cloud-specific worker SKU (cloud="{self.config.cloud}").
            node_type_id: "{node_type_id}"

      tasks:
        - task_key: "run_{workflow_name}"
          job_cluster_key: "main"
          spark_python_task:
            python_file: ../src/{workflow_name}.py
          libraries:
            - pypi:
                package: "pyspark>={self.config.spark_version}"

      parameters:
        - name: "catalog"
          default: "{catalog}"
        - name: "schema"
          default: "{schema}"

      tags:
        source: "alteryx_migration"
        tool: "a2d"
"""
        return GeneratedFile(
            filename=f"resources/{workflow_name}_job.yml",
            content=content,
            file_type="yaml",
        )

    def _generate_env_yml(self, workflow_name: str, env: str) -> GeneratedFile:
        """Generate environment-specific config."""
        catalog = self.config.catalog_name
        schema = self.config.schema_name

        # Adjust for environment
        env_catalog = f"{catalog}_{env}" if env != "prod" else catalog
        workers = {"dev": 1, "staging": 2, "prod": 4}.get(env, 2)

        content = f"""# {env.capitalize()} environment configuration
# Generated by a2d

targets:
  {env}:
    mode: {"development" if env == "dev" else "production"}
    default: {str(env == "dev").lower()}
    workspace:
      host: ${{var.{env}_workspace_host}}

    variables:
      catalog: "{env_catalog}"
      schema: "{schema}"
      num_workers: {workers}
"""
        return GeneratedFile(
            filename=f"environments/{env}.yml",
            content=content,
            file_type="yaml",
        )

    @staticmethod
    def _find_main_code(output: GeneratedOutput) -> str | None:
        """Find the main Python or SQL code file from generated output."""
        for f in output.files:
            if f.file_type in ("python", "sql") and not f.filename.endswith(".json"):
                return f.content
        return None
