"""Delta Live Tables pipeline code generator.

Each IR node becomes a ``@dlt.table`` decorated function whose body reads
from upstream tables via ``dlt.read()`` and returns a DataFrame.
"""

from __future__ import annotations

import logging
import re

from a2d.__about__ import __version__
from a2d.config import ConversionConfig
from a2d.expressions.base_translator import BaseTranslationError
from a2d.expressions.parser import ParserError
from a2d.expressions.translator import PySparkTranslator
from a2d.generators.base import CodeGenerator, GeneratedFile, GeneratedOutput
from a2d.utils.types import alteryx_fmt_to_spark
from a2d.ir.graph import WorkflowDAG
from a2d.ir.nodes import (
    ABAnalysisNode,
    AggAction,
    AppendClusterNode,
    AppendFieldsNode,
    ARIMANode,
    AutoFieldNode,
    BoostedModelNode,
    BrowseNode,
    BufferNode,
    ChartNode,
    CloudStorageNode,
    CommentNode,
    CountRecordsNode,
    CountRegressionNode,
    CreatePointsNode,
    CrossTabNode,
    CrossValidationNode,
    DataCleansingNode,
    DateTimeNode,
    DecisionTreeNode,
    DistanceNode,
    DownloadNode,
    DynamicInputNode,
    DynamicOutputNode,
    EmailOutputNode,
    ETSNode,
    FieldAction,
    FieldSummaryNode,
    FilterNode,
    FindNearestNeighborsNode,
    FindNearestNode,
    FindReplaceNode,
    ForestModelNode,
    FormulaNode,
    GammaRegressionNode,
    GenerateRowsNode,
    GeocoderNode,
    ImputationNode,
    IRNode,
    JoinMultipleNode,
    JoinNode,
    JsonParseNode,
    KCentroidsDiagnosticsNode,
    KCentroidsNode,
    LiftChartNode,
    LinearRegressionNode,
    LiteralDataNode,
    LogisticRegressionNode,
    MacroIONode,
    MakeGridNode,
    MeansTestNode,
    ModelCoefficientsNode,
    ModelComparisonNode,
    MultiFieldFormulaNode,
    MultiRowFormulaNode,
    NaiveBayesNode,
    NeuralNetworkNode,
    PrincipalComponentsNode,
    PythonToolNode,
    ReadNode,
    RecordIDNode,
    RegExNode,
    ReportNode,
    RunCommandNode,
    RunningTotalNode,
    SampleNode,
    ScoreModelNode,
    SelectNode,
    SortNode,
    SpatialMatchNode,
    SplineModelNode,
    StepwiseNode,
    SummarizeNode,
    SupportVectorMachineNode,
    TextToColumnsNode,
    TileNode,
    TradeAreaNode,
    TransposeNode,
    TSForecastNode,
    UnionNode,
    UniqueNode,
    UnsupportedNode,
    VarianceInflationFactorsNode,
    WeightedAverageNode,
    WidgetNode,
    WorkflowControlNode,
    WriteNode,
    XMLParseNode,
)

logger = logging.getLogger("a2d.generators.dlt")


def _sanitize_name(name: str) -> str:
    """Turn an arbitrary string into a valid Python identifier."""
    name = re.sub(r"[^a-zA-Z0-9_]", "_", name)
    if name and name[0].isdigit():
        name = f"t_{name}"
    return name.lower()


class DLTGenerator(CodeGenerator):
    """Generate Delta Live Tables pipeline code."""

    def __init__(self, config: ConversionConfig) -> None:
        super().__init__(config)
        self._translator = PySparkTranslator()

    def generate(self, dag: WorkflowDAG, workflow_name: str = "workflow") -> GeneratedOutput:
        ordered_nodes = dag.topological_order()
        warnings: list[str] = []
        table_name_map: dict[int, str] = {}  # node_id -> dlt table name
        functions: list[str] = []
        node_count = 0

        for node in ordered_nodes:
            if isinstance(node, CommentNode):
                continue

            table_name = self._make_table_name(node)
            table_name_map[node.node_id] = table_name

            # Resolve upstream table names
            input_tables = self._resolve_input_tables(node.node_id, dag, table_name_map)

            func_code, func_warnings = self._generate_dlt_function(node, table_name, input_tables)
            functions.append(func_code)
            warnings.extend(func_warnings)
            node_count += 1

        # Build full file
        header_lines = [
            "# Databricks notebook source",
            f"# Delta Live Tables pipeline migrated from: {workflow_name}",
            f"# Generated by: a2d v{__version__}",
            "",
            "import dlt",
            "from pyspark.sql import functions as F",
            "from pyspark.sql import Window",
            "",
        ]

        content = "\n".join(header_lines) + "\n" + "\n\n".join(functions) + "\n"

        files = [
            GeneratedFile(
                filename=f"{workflow_name}_dlt.py",
                content=content,
                file_type="python",
            )
        ]

        stats = {
            "total_nodes": node_count,
            "total_tables": len(table_name_map),
            "warnings": len(warnings),
        }

        return GeneratedOutput(files=files, warnings=warnings, stats=stats)

    # -- Helpers ------------------------------------------------------------

    def _make_table_name(self, node: IRNode) -> str:
        tool = node.original_tool_type or type(node).__name__.replace("Node", "")
        return _sanitize_name(f"step_{node.node_id}_{tool}")

    def _resolve_input_tables(self, node_id: int, dag: WorkflowDAG, table_name_map: dict[int, str]) -> dict[str, str]:
        """Map destination anchors to upstream DLT table names."""
        result: dict[str, str] = {}
        preds = dag.get_predecessors(node_id)
        for pred in preds:
            edge_info = dag.get_edge_info(pred.node_id, node_id)
            dest_anchor = edge_info.destination_anchor
            tbl = table_name_map.get(pred.node_id, f"step_{pred.node_id}_unknown")
            result[dest_anchor] = tbl
        return result

    def _generate_dlt_function(
        self,
        node: IRNode,
        table_name: str,
        input_tables: dict[str, str],
    ) -> tuple[str, list[str]]:
        """Generate a @dlt.table function for a single node.

        Returns (code_string, warnings_list).
        """
        warnings: list[str] = []
        comment = node.annotation or node.original_tool_type or type(node).__name__
        func_name = _sanitize_name(table_name)

        # Get the body lines
        body, body_warnings = self._node_body(node, input_tables)
        warnings.extend(body_warnings)

        lines = [
            f'@dlt.table(name="{table_name}", comment="{comment}")',
            f"def {func_name}():",
        ]
        for line in body:
            lines.append(f"    {line}")

        return "\n".join(lines), warnings

    def _get_single_input_read(self, input_tables: dict[str, str]) -> str:
        """Return a dlt.read() call for the single input table."""
        if "Input" in input_tables:
            return f'dlt.read("{input_tables["Input"]}")'
        if input_tables:
            first = next(iter(input_tables.values()))
            return f'dlt.read("{first}")'
        return "spark.createDataFrame([], schema=[])"

    def _node_body(self, node: IRNode, input_tables: dict[str, str]) -> tuple[list[str], list[str]]:
        """Generate the body lines of a DLT function."""
        warnings: list[str] = []

        if isinstance(node, ReadNode):
            return self._body_ReadNode(node), warnings

        if isinstance(node, WriteNode):
            inp = self._get_single_input_read(input_tables)
            return [f"return {inp}  # Write target: {node.file_path or node.table_name}"], warnings

        if isinstance(node, LiteralDataNode):
            rows_repr = repr(node.data_rows) if node.data_rows else "[]"
            schema_repr = repr(node.field_names) if node.field_names else "[]"
            return [f"return spark.createDataFrame({rows_repr}, schema={schema_repr})"], warnings

        if isinstance(node, BrowseNode):
            inp = self._get_single_input_read(input_tables)
            return [f"return {inp}  # Browse / preview"], warnings

        if isinstance(node, FilterNode):
            inp = self._get_single_input_read(input_tables)
            if not node.expression or not node.expression.strip():
                warnings.append(
                    f"Filter node {node.node_id} has no expression — returning all rows"
                )
                return [
                    f"# TODO: Filter node {node.node_id} — expression could not be extracted from workflow XML",
                    f"return {inp}",
                ], warnings
            try:
                expr = self._translator.translate_string(node.expression)
            except (BaseTranslationError, ParserError):
                expr = f'F.expr("{node.expression}")'
                warnings.append(f"Filter expression fallback for node {node.node_id}")
            return [f"return {inp}.filter({expr})"], warnings

        if isinstance(node, FormulaNode):
            inp = self._get_single_input_read(input_tables)
            lines = [f"df = {inp}"]
            for formula in node.formulas:
                try:
                    expr = self._translator.translate_string(formula.expression)
                except (BaseTranslationError, ParserError):
                    expr = f'F.expr("{formula.expression}")'
                    warnings.append(f"Formula fallback: {formula.output_field}")
                lines.append(f'df = df.withColumn("{formula.output_field}", {expr})')
            lines.append("return df")
            return lines, warnings

        if isinstance(node, SelectNode):
            inp = self._get_single_input_read(input_tables)
            lines = [f"df = {inp}"]
            for op in node.field_operations:
                if not op.selected or op.action == FieldAction.DESELECT:
                    lines.append(f'df = df.drop("{op.field_name}")')
                elif op.action == FieldAction.RENAME and op.rename_to:
                    lines.append(f'df = df.withColumnRenamed("{op.field_name}", "{op.rename_to}")')
            lines.append("return df")
            return lines, warnings

        if isinstance(node, SortNode):
            inp = self._get_single_input_read(input_tables)
            sort_parts = []
            for sf in node.sort_fields:
                direction = "asc" if sf.ascending else "desc"
                sort_parts.append(f'F.col("{sf.field_name}").{direction}()')
            return [f"return {inp}.orderBy({', '.join(sort_parts)})"], warnings

        if isinstance(node, SampleNode):
            inp = self._get_single_input_read(input_tables)
            if node.n_records:
                return [f"return {inp}.limit({node.n_records})"], warnings
            if node.percentage:
                frac = node.percentage / 100.0 if node.percentage > 1 else node.percentage
                return [f"return {inp}.sample(fraction={frac})"], warnings
            return [f"return {inp}.limit(100)"], warnings

        if isinstance(node, UniqueNode):
            inp = self._get_single_input_read(input_tables)
            keys = repr(node.key_fields)
            return [f"return {inp}.dropDuplicates({keys})"], warnings

        if isinstance(node, RecordIDNode):
            inp = self._get_single_input_read(input_tables)
            return [
                f'return {inp}.withColumn("{node.output_field}", F.monotonically_increasing_id() + {node.starting_value})'
            ], warnings

        if isinstance(node, AutoFieldNode):
            inp = self._get_single_input_read(input_tables)
            return [f"return {inp}  # AutoField passthrough"], warnings

        if isinstance(node, JoinNode):
            left_tbl = input_tables.get("Left", input_tables.get("Input", "MISSING"))
            right_tbl = input_tables.get("Right", "MISSING")
            left_read = f'dlt.read("{left_tbl}")'
            right_read = f'dlt.read("{right_tbl}")'
            if node.join_keys:
                cond_parts = [
                    f'{left_read.replace("dlt.read", "left")}["{jk.left_field}"] == right["{jk.right_field}"]'
                    for jk in node.join_keys
                ]
                # Simplify: use column name join
                key_names = [jk.left_field for jk in node.join_keys]
                if all(jk.left_field == jk.right_field for jk in node.join_keys):
                    cond = repr(key_names)
                else:
                    cond_parts = [f'left["{jk.left_field}"] == right["{jk.right_field}"]' for jk in node.join_keys]
                    cond = " & ".join(f"({cp})" for cp in cond_parts)
            else:
                cond = "F.lit(True)"
            jtype = node.join_type or "inner"
            lines = [
                f"left = {left_read}",
                f"right = {right_read}",
                f'return left.join(right, {cond}, "{jtype}")',
            ]
            return lines, warnings

        if isinstance(node, UnionNode):
            tables = list(input_tables.values())
            if not tables:
                return ["return spark.createDataFrame([], schema=[])"], warnings
            lines = [f'df = dlt.read("{tables[0]}")']
            allow = "True" if node.allow_missing else "False"
            for t in tables[1:]:
                lines.append(f'df = df.unionByName(dlt.read("{t}"), allowMissingColumns={allow})')
            lines.append("return df")
            return lines, warnings

        if isinstance(node, AppendFieldsNode):
            target_tbl = input_tables.get("Target", input_tables.get("Input", "MISSING"))
            source_tbl = input_tables.get("Source", "MISSING")
            return [f'return dlt.read("{target_tbl}").crossJoin(dlt.read("{source_tbl}"))'], warnings

        if isinstance(node, SummarizeNode):
            inp = self._get_single_input_read(input_tables)
            gb = []
            aggs = []
            agg_map = {
                AggAction.SUM: "F.sum",
                AggAction.COUNT: "F.count",
                AggAction.MIN: "F.min",
                AggAction.MAX: "F.max",
                AggAction.AVG: "F.avg",
                AggAction.FIRST: "F.first",
                AggAction.LAST: "F.last",
            }
            for a in node.aggregations:
                if a.action == AggAction.GROUP_BY:
                    gb.append(f'"{a.field_name}"')
                elif a.action in agg_map:
                    alias = a.output_field_name or f"{a.action.value}_{a.field_name}"
                    aggs.append(f'{agg_map[a.action]}("{a.field_name}").alias("{alias}")')
                else:
                    alias = a.output_field_name or f"{a.action.value}_{a.field_name}"
                    aggs.append(f'F.count("{a.field_name}").alias("{alias}")')
            gb_str = ", ".join(gb)
            agg_str = ", ".join(aggs) if aggs else 'F.count("*").alias("count")'
            if gb:
                return [f"return {inp}.groupBy({gb_str}).agg({agg_str})"], warnings
            return [f"return {inp}.agg({agg_str})"], warnings

        if isinstance(node, CrossTabNode):
            inp = self._get_single_input_read(input_tables)
            gcols = ", ".join(f'"{g}"' for g in node.group_fields)
            agg_f = node.aggregation.lower() if node.aggregation else "sum"
            return [
                f'return {inp}.groupBy({gcols}).pivot("{node.header_field}").agg(F.{agg_f}("{node.value_field}"))'
            ], warnings

        if isinstance(node, CountRecordsNode):
            inp = self._get_single_input_read(input_tables)
            return [f'return spark.createDataFrame([({inp}.count(),)], ["{node.output_field}"])'], warnings

        if isinstance(node, MultiRowFormulaNode):
            inp = self._get_single_input_read(input_tables)
            lines = [f"df = {inp}"]
            if node.group_fields:
                partition = ", ".join(f'"{gf}"' for gf in node.group_fields)
                lines.append(f"_window = Window.partitionBy({partition}).orderBy(F.monotonically_increasing_id())")
            else:
                lines.append("_window = Window.orderBy(F.monotonically_increasing_id())")
            try:
                expr = self._translator.translate_string(node.expression)
                expr = expr.replace(".over(window)", ".over(_window)")
            except (BaseTranslationError, ParserError):
                expr = f'F.expr("{node.expression}")'
                warnings.append(f"MultiRowFormula expression fallback for node {node.node_id}")
            lines.append(f'df = df.withColumn("{node.output_field}", {expr})')
            lines.append("return df")
            return lines, warnings

        if isinstance(node, MultiFieldFormulaNode):
            inp = self._get_single_input_read(input_tables)
            lines = [f"df = {inp}"]
            for fld in node.fields:
                try:
                    expr_str = node.expression.replace("[_CurrentField_]", f"[{fld}]")
                    expr = self._translator.translate_string(expr_str)
                except (BaseTranslationError, ParserError):
                    expr = f'F.col("{fld}")'
                    warnings.append(f"MultiFieldFormula fallback for field '{fld}'")
                output_name = f"{fld}_out" if node.copy_output else fld
                lines.append(f'df = df.withColumn("{output_name}", {expr})')
            lines.append("return df")
            return lines, warnings

        if isinstance(node, DataCleansingNode):
            inp = self._get_single_input_read(input_tables)
            lines = [f"df = {inp}"]
            for fld in node.fields:
                if node.trim_whitespace:
                    lines.append(f'df = df.withColumn("{fld}", F.trim(F.col("{fld}")))')
                if node.remove_null and node.replace_nulls_with is not None:
                    lines.append(f'df = df.na.fill({{"{fld}": "{node.replace_nulls_with}"}})')
                elif node.remove_null:
                    lines.append(f'df = df.na.fill({{"{fld}": ""}})')
                if node.modify_case == "upper":
                    lines.append(f'df = df.withColumn("{fld}", F.upper(F.col("{fld}")))')
                elif node.modify_case == "lower":
                    lines.append(f'df = df.withColumn("{fld}", F.lower(F.col("{fld}")))')
                elif node.modify_case == "title":
                    lines.append(f'df = df.withColumn("{fld}", F.initcap(F.col("{fld}")))')
            lines.append("return df")
            return lines, warnings

        if isinstance(node, GenerateRowsNode):
            output_field = node.output_field or "GeneratedRow"
            import re as _re
            range_match = _re.search(r'(\w+)\s*<=?\s*(\d+)', node.condition_expression)
            init_match = _re.search(r'(\w+)\s*=\s*(\d+)', node.init_expression)
            if init_match and range_match:
                start_val = int(init_match.group(2))
                end_val = int(range_match.group(2))
                if '<=' in node.condition_expression:
                    end_val += 1
                return [f'return spark.range({start_val}, {end_val}).withColumnRenamed("id", "{output_field}")'], warnings
            return [f'return spark.range(0, 1000).withColumnRenamed("id", "{output_field}")  # Adjust range as needed'], warnings

        if isinstance(node, FindReplaceNode):
            target_tbl = input_tables.get("Input", input_tables.get("Target", "MISSING"))
            lookup_tbl = input_tables.get("Source", input_tables.get("Right", target_tbl))
            find_field = node.find_field or "find_field"
            replace_field = node.replace_field or "replace_field"
            lines = [
                f'main = dlt.read("{target_tbl}")',
                f'lookup = dlt.read("{lookup_tbl}").select(F.col("{find_field}").alias("_find_val"), F.col("{replace_field}").alias("_replace_val"))',
                f'df = main.join(lookup, main["{find_field}"] == lookup["_find_val"], "left")',
                f'df = df.withColumn("{find_field}", F.coalesce(F.col("_replace_val"), F.col("{find_field}")))',
                'return df.drop("_find_val", "_replace_val")',
            ]
            return lines, warnings

        if isinstance(node, JoinMultipleNode):
            tables = list(input_tables.values())
            if len(tables) < 2:
                inp = self._get_single_input_read(input_tables)
                return [f"return {inp}"], warnings
            join_type = node.join_type or "inner"
            lines = [f'df = dlt.read("{tables[0]}")']
            for tbl in tables[1:]:
                if node.join_keys:
                    key_parts = [f'df["{jk.left_field}"] == right["{jk.right_field}"]' for jk in node.join_keys]
                    cond = " & ".join(f"({kp})" for kp in key_parts)
                    lines.append(f'right = dlt.read("{tbl}")')
                    lines.append(f'df = df.join(right, {cond}, "{join_type}")')
                else:
                    lines.append(f'df = df.join(dlt.read("{tbl}"), "{join_type}")')
            lines.append("return df")
            return lines, warnings

        if isinstance(node, RegExNode):
            inp = self._get_single_input_read(input_tables)
            if node.mode == "replace":
                return [f'return {inp}.withColumn("{node.field_name}", F.regexp_replace(F.col("{node.field_name}"), "{node.expression}", "{node.replacement}"))'], warnings
            elif node.mode == "parse":
                lines = [f"df = {inp}"]
                for idx, out_field in enumerate(node.output_fields):
                    lines.append(f'df = df.withColumn("{out_field}", F.regexp_extract(F.col("{node.field_name}"), "{node.expression}", {idx + 1}))')
                lines.append("return df")
                return lines, warnings
            elif node.mode == "match":
                return [f'return {inp}.withColumn("_regex_match", F.col("{node.field_name}").rlike("{node.expression}"))'], warnings
            return [f"return {inp}  # RegEx mode '{node.mode}' - manual conversion needed"], warnings

        if isinstance(node, TextToColumnsNode):
            inp = self._get_single_input_read(input_tables)
            root = node.output_root_name or node.field_name
            if node.split_to == "rows":
                return [f'return {inp}.withColumn("{root}", F.explode(F.split(F.col("{node.field_name}"), "{node.delimiter}")))'], warnings
            lines = [f"df = {inp}", f'_split = F.split(F.col("{node.field_name}"), "{node.delimiter}")']
            num = node.num_columns or 5
            for i in range(num):
                lines.append(f'df = df.withColumn("{root}_{i + 1}", _split[{i}])')
            lines.append("return df")
            return lines, warnings

        if isinstance(node, DateTimeNode):
            inp = self._get_single_input_read(input_tables)
            out_field = node.output_field or f"{node.input_field}_converted"
            fmt = alteryx_fmt_to_spark(node.format_string or "yyyy-MM-dd")
            if node.conversion_mode == "parse":
                return [f'return {inp}.withColumn("{out_field}", F.to_date(F.col("{node.input_field}"), "{fmt}"))'], warnings
            elif node.conversion_mode == "format":
                return [f'return {inp}.withColumn("{out_field}", F.date_format(F.col("{node.input_field}"), "{fmt}"))'], warnings
            return [f'return {inp}.withColumn("{out_field}", F.col("{node.input_field}"))'], warnings

        if isinstance(node, JsonParseNode):
            inp = self._get_single_input_read(input_tables)
            out_field = node.output_field or f"{node.input_field}_parsed"
            return [f'return {inp}.withColumn("{out_field}", F.get_json_object(F.col("{node.input_field}"), "$"))'], warnings

        if isinstance(node, TransposeNode):
            inp = self._get_single_input_read(input_tables)
            if node.data_fields:
                key_cols = ", ".join(f'"`{kf}`"' for kf in node.key_fields) if node.key_fields else ""
                cols_str = ", ".join(f"'{df}', `{df}`" for df in node.data_fields)
                expr = f'"stack({len(node.data_fields)}, {cols_str}) as (`{node.header_name}`, `{node.value_name}`)"'
                key_part = f"{key_cols}, " if key_cols else ""
                return [f'return {inp}.selectExpr({key_part}{expr})'], warnings
            return [f"return {inp}  # Transpose: determine data columns at runtime"], warnings

        if isinstance(node, RunningTotalNode):
            inp = self._get_single_input_read(input_tables)
            lines = [f"df = {inp}"]
            if node.group_fields:
                partition = ", ".join(f'"{gf}"' for gf in node.group_fields)
                lines.append(f"_window = Window.partitionBy({partition}).orderBy(F.monotonically_increasing_id()).rowsBetween(Window.unboundedPreceding, Window.currentRow)")
            else:
                lines.append("_window = Window.orderBy(F.monotonically_increasing_id()).rowsBetween(Window.unboundedPreceding, Window.currentRow)")
            func_map = {"Sum": "F.sum", "Avg": "F.avg", "Count": "F.count", "Min": "F.min", "Max": "F.max"}
            for rf in node.running_fields:
                func = func_map.get(rf.running_type, "F.sum")
                alias = rf.output_field_name or f"Running{rf.running_type}_{rf.field_name}"
                lines.append(f'df = df.withColumn("{alias}", {func}("{rf.field_name}").over(_window))')
            lines.append("return df")
            return lines, warnings

        if isinstance(node, PythonToolNode):
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"PythonTool (node {node.node_id}) requires manual review")
            return ["# PythonTool: manual review required", f"return {inp}"], warnings

        if isinstance(node, DownloadNode):
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"DownloadTool (node {node.node_id}) requires manual conversion")
            return ["# DownloadTool: replace with HTTP UDF or external access", f"return {inp}"], warnings

        if isinstance(node, RunCommandNode):
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"RunCommand (node {node.node_id}) not supported in DLT")
            return ["# RunCommand: not supported in DLT pipelines", f"return {inp}"], warnings

        if isinstance(node, ImputationNode):
            inp = self._get_single_input_read(input_tables)
            lines = [f"df = {inp}"]
            if node.method == "custom" and node.custom_value is not None:
                fill_dict = ", ".join(f'"{f}": "{node.custom_value}"' for f in node.fields)
                lines.append(f"df = df.na.fill({{{fill_dict}}})")
            elif node.method in ("mean", "avg"):
                for fld in node.fields:
                    lines.append(f'_mean = df.agg(F.avg("{fld}")).first()[0]')
                    lines.append(f'df = df.na.fill({{"{fld}": _mean}})')
            elif node.method == "median":
                for fld in node.fields:
                    lines.append(f'_median = df.approxQuantile("{fld}", [0.5], 0.001)[0]')
                    lines.append(f'df = df.na.fill({{"{fld}": _median}})')
            elif node.method == "mode":
                for fld in node.fields:
                    lines.append(f'_mode = df.groupBy("{fld}").count().orderBy(F.desc("count")).first()[0]')
                    lines.append(f'df = df.na.fill({{"{fld}": _mode}})')
            else:
                lines.append('df = df.na.fill("")')
            lines.append("return df")
            return lines, warnings

        if isinstance(node, XMLParseNode):
            inp = self._get_single_input_read(input_tables)
            lines = [f"df = {inp}"]
            if node.xpath_expressions:
                for xpath, name in node.xpath_expressions:
                    lines.append(f'df = df.withColumn("{name}", F.xpath_string(F.col("{node.input_field}"), F.lit("{xpath}")))')
            elif node.output_field:
                lines.append(f'df = df.withColumn("{node.output_field}", F.col("{node.input_field}"))')
            lines.append("return df")
            warnings.append(f"XMLParse (node {node.node_id}): verify xpath_string availability") if node.xpath_expressions else None
            return lines, warnings

        if isinstance(node, TileNode):
            inp = self._get_single_input_read(input_tables)
            order = f'"{node.order_field}"' if node.order_field else f'"{node.tile_field}"' if node.tile_field else "F.monotonically_increasing_id()"
            if node.group_fields:
                partition = ", ".join(f'"{gf}"' for gf in node.group_fields)
                window = f"Window.partitionBy({partition}).orderBy({order})"
            else:
                window = f"Window.orderBy({order})"
            return [f'return {inp}.withColumn("{node.output_field}", F.ntile({node.tile_count}).over({window}))'], warnings

        if isinstance(node, WeightedAverageNode):
            inp = self._get_single_input_read(input_tables)
            agg_expr = f'(F.sum(F.col("{node.value_field}") * F.col("{node.weight_field}")) / F.sum(F.col("{node.weight_field}"))).alias("{node.output_field}")'
            if node.group_fields:
                gb = ", ".join(f'"{gf}"' for gf in node.group_fields)
                return [f"return {inp}.groupBy({gb}).agg({agg_expr})"], warnings
            return [f"return {inp}.agg({agg_expr})"], warnings

        if isinstance(node, DynamicInputNode):
            fmt = node.file_format or "csv"
            pattern = node.file_path_pattern or "*.csv"
            warnings.append(f"DynamicInput (node {node.node_id}): adjust path for Databricks")
            return [f'return spark.read.format("{fmt}").option("header", "true").load("{pattern}")'], warnings

        if isinstance(node, DynamicOutputNode):
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"DynamicOutput (node {node.node_id}): write operation in DLT needs review")
            return ["# DynamicOutput: write operations need manual review in DLT", f"return {inp}"], warnings

        if isinstance(node, WorkflowControlNode):
            inp = self._get_single_input_read(input_tables) if input_tables else "spark.createDataFrame([], schema=[])"
            return [f"# {node.original_tool_type}: no DLT equivalent", f"return {inp}"], warnings

        if isinstance(node, MacroIONode):
            if node.direction == "input":
                return [f'# MacroInput: use dbutils.widgets.text("{node.field_name}")', "return spark.createDataFrame([], schema=[])"], warnings
            inp = self._get_single_input_read(input_tables) if input_tables else "spark.createDataFrame([], schema=[])"
            return [f"return {inp}  # MacroOutput passthrough"], warnings

        if isinstance(node, FieldSummaryNode):
            inp = self._get_single_input_read(input_tables)
            return [f"return {inp}.describe()"], warnings

        if isinstance(node, WidgetNode):
            return [f'# Widget ({node.widget_type}): use dbutils.widgets', "return spark.createDataFrame([], schema=[])"], warnings

        if isinstance(node, CloudStorageNode):
            if node.provider == "s3":
                prefix = "s3://"
            elif node.provider == "azure":
                prefix = "abfss://"
            else:
                prefix = ""
            full_path = f"{prefix}{node.bucket_or_container}/{node.path}" if node.bucket_or_container else node.path
            fmt = node.file_format or "csv"
            if node.direction == "input":
                return [f'return spark.read.format("{fmt}").option("header", "true").load("{full_path}")'], warnings
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"CloudStorage output (node {node.node_id}): write in DLT needs review")
            return [f"return {inp}  # CloudStorage output"], warnings

        if isinstance(node, ChartNode):
            inp = self._get_single_input_read(input_tables)
            return [f"# Chart: {node.chart_type or 'auto'} - not supported in DLT", f"return {inp}"], warnings

        if isinstance(node, ReportNode):
            inp = self._get_single_input_read(input_tables)
            return [f"# Report ({node.report_type}): not supported in DLT", f"return {inp}"], warnings

        if isinstance(node, EmailOutputNode):
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"EmailOutput (node {node.node_id}): not supported in DLT")
            return ["# EmailOutput: not supported in DLT", f"return {inp}"], warnings

        # -- Spatial tools --------------------------------------------------
        if isinstance(node, BufferNode):
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"Buffer (node {node.node_id}): requires Sedona/GeoMesa UDFs")
            return [
                f"# Buffer: create {node.buffer_distance} {node.buffer_units} buffer around {node.input_field}",
                f'return {inp}.withColumn("{node.input_field}", F.expr("ST_Buffer({node.input_field}, {node.buffer_distance})"))',
            ], warnings

        if isinstance(node, SpatialMatchNode):
            target_tbl = input_tables.get("Target", input_tables.get("Input", "MISSING"))
            universe_tbl = input_tables.get("Universe", input_tables.get("Right", target_tbl))
            warnings.append(f"SpatialMatch (node {node.node_id}): requires Sedona/GeoMesa UDFs")
            return [
                f"# SpatialMatch: {node.match_type} between {node.spatial_field_target} and {node.spatial_field_universe}",
                f'target = dlt.read("{target_tbl}")',
                f'universe = dlt.read("{universe_tbl}")',
                f'return target.join(universe, F.expr("ST_{node.match_type.capitalize()}({node.spatial_field_target}, {node.spatial_field_universe})"), "inner")',
            ], warnings

        if isinstance(node, CreatePointsNode):
            inp = self._get_single_input_read(input_tables)
            return [
                f'return {inp}.withColumn("{node.output_field}", F.expr("ST_Point({node.lon_field}, {node.lat_field})"))',
            ], warnings

        if isinstance(node, DistanceNode):
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"Distance (node {node.node_id}): requires Sedona/GeoMesa UDFs")
            return [
                f"# Distance: {node.distance_units} between {node.source_field} and {node.target_field}",
                f'return {inp}.withColumn("{node.output_field}", F.expr("ST_Distance({node.source_field}, {node.target_field})"))',
            ], warnings

        if isinstance(node, FindNearestNode):
            target_tbl = input_tables.get("Target", input_tables.get("Input", "MISSING"))
            universe_tbl = input_tables.get("Universe", input_tables.get("Right", target_tbl))
            warnings.append(f"FindNearest (node {node.node_id}): requires Sedona/GeoMesa spatial join")
            lines = [
                f"# FindNearest: top {node.max_matches} within {node.max_distance or 'unlimited'} {node.distance_units}",
                f'target = dlt.read("{target_tbl}")',
                f'universe = dlt.read("{universe_tbl}")',
                f'df = target.crossJoin(universe).withColumn("{node.output_distance_field}", F.expr("ST_Distance({node.target_field}, {node.universe_field})"))',
            ]
            if node.max_distance is not None:
                lines.append(f'df = df.filter(F.col("{node.output_distance_field}") <= {node.max_distance})')
            lines.append(f"_window = Window.partitionBy(target.columns).orderBy(F.col(\"{node.output_distance_field}\").asc())")
            lines.append(f"df = df.withColumn(\"_rank\", F.row_number().over(_window)).filter(F.col(\"_rank\") <= {node.max_matches}).drop(\"_rank\")")
            lines.append("return df")
            return lines, warnings

        if isinstance(node, GeocoderNode):
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"Geocoder (node {node.node_id}): requires external geocoding service UDF")
            addr_parts = [f for f in [node.address_field, node.city_field, node.state_field, node.zip_field, node.country_field] if f]
            concat_expr = ", ".join(f'F.col("{f}")' for f in addr_parts)
            return [
                "# Geocoder: convert address to lat/lon - requires geocoding UDF",
                f"df = {inp}",
                f'df = df.withColumn("{node.output_lat_field}", F.lit(None).cast("double"))  # TODO: replace with geocoding UDF',
                f'df = df.withColumn("{node.output_lon_field}", F.lit(None).cast("double"))  # TODO: replace with geocoding UDF',
                "return df",
            ], warnings

        if isinstance(node, TradeAreaNode):
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"TradeArea (node {node.node_id}): requires Sedona/GeoMesa UDFs")
            return [
                f"# TradeArea: {node.ring_count} ring(s) of {node.radius} {node.radius_units} around {node.input_field}",
                f'return {inp}.withColumn("{node.output_field}", F.expr("ST_Buffer({node.input_field}, {node.radius})"))',
            ], warnings

        if isinstance(node, MakeGridNode):
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"MakeGrid (node {node.node_id}): requires Sedona/GeoMesa UDFs")
            return [
                f"# MakeGrid: {node.grid_size} {node.grid_units} grid over {node.extent_field}",
                "# TODO: implement grid generation with Sedona ST_SquareGrid or equivalent",
                f'return {inp}.withColumn("{node.output_field}", F.lit(None))  # placeholder',
            ], warnings

        # -- Predictive / ML tools ------------------------------------------
        if isinstance(node, DecisionTreeNode):
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"DecisionTree (node {node.node_id}): MLlib model training is not idiomatic in DLT pipelines")
            features = repr(node.feature_fields)
            return [
                f"# DecisionTree ({node.model_type}): MLlib training is not idiomatic in DLT.",
                "# Consider training in a separate notebook and loading the model for scoring.",
                f"# Target: {node.target_field}, Features: {features}, max_depth={node.max_depth}",
                f"return {inp}  # passthrough - train model outside DLT",
            ], warnings

        if isinstance(node, ForestModelNode):
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"ForestModel (node {node.node_id}): MLlib model training is not idiomatic in DLT pipelines")
            features = repr(node.feature_fields)
            return [
                f"# RandomForest ({node.model_type}): MLlib training is not idiomatic in DLT.",
                "# Consider training in a separate notebook and loading the model for scoring.",
                f"# Target: {node.target_field}, Features: {features}, num_trees={node.num_trees}, max_depth={node.max_depth}",
                f"return {inp}  # passthrough - train model outside DLT",
            ], warnings

        if isinstance(node, LinearRegressionNode):
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"LinearRegression (node {node.node_id}): MLlib model training is not idiomatic in DLT pipelines")
            features = repr(node.feature_fields)
            return [
                "# LinearRegression: MLlib training is not idiomatic in DLT.",
                "# Consider training in a separate notebook and loading the model for scoring.",
                f"# Target: {node.target_field}, Features: {features}, regularization={node.regularization}",
                f"return {inp}  # passthrough - train model outside DLT",
            ], warnings

        if isinstance(node, LogisticRegressionNode):
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"LogisticRegression (node {node.node_id}): MLlib model training is not idiomatic in DLT pipelines")
            features = repr(node.feature_fields)
            return [
                "# LogisticRegression: MLlib training is not idiomatic in DLT.",
                "# Consider training in a separate notebook and loading the model for scoring.",
                f"# Target: {node.target_field}, Features: {features}, max_iterations={node.max_iterations}",
                f"return {inp}  # passthrough - train model outside DLT",
            ], warnings

        if isinstance(node, ScoreModelNode):
            inp = self._get_single_input_read(input_tables)
            model_ref = node.model_reference or "UNKNOWN_MODEL"
            features = repr(node.feature_fields)
            warnings.append(f"ScoreModel (node {node.node_id}): load trained model from MLflow or DBFS")
            return [
                "# ScoreModel: apply pre-trained model for scoring",
                f"# Model reference: {model_ref}, Features: {features}",
                f"df = {inp}",
                f'# TODO: load model via mlflow.spark.load_model("{model_ref}") and call model.transform(df)',
                f'df = df.withColumn("{node.output_field}", F.lit(None))  # placeholder until model is loaded',
                "return df",
            ], warnings

        if isinstance(node, BoostedModelNode):
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"BoostedModel (node {node.node_id}): MLlib model training is not idiomatic in DLT pipelines")
            return [
                f"# BoostedModel ({node.model_type}): MLlib training is not idiomatic in DLT.",
                f"# Target: {node.target_field}, Features: {node.feature_fields!r}, iterations={node.num_iterations}",
                f"return {inp}  # passthrough - train model outside DLT",
            ], warnings

        if isinstance(node, NaiveBayesNode):
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"NaiveBayes (node {node.node_id}): MLlib model training is not idiomatic in DLT pipelines")
            return [
                "# NaiveBayes: MLlib training is not idiomatic in DLT.",
                f"# Target: {node.target_field}, Features: {node.feature_fields!r}",
                f"return {inp}  # passthrough - train model outside DLT",
            ], warnings

        if isinstance(node, SupportVectorMachineNode):
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"SVM (node {node.node_id}): MLlib model training is not idiomatic in DLT pipelines")
            return [
                "# SupportVectorMachine: MLlib training is not idiomatic in DLT.",
                f"# Target: {node.target_field}, Features: {node.feature_fields!r}",
                f"return {inp}  # passthrough - train model outside DLT",
            ], warnings

        if isinstance(node, NeuralNetworkNode):
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"NeuralNetwork (node {node.node_id}): MLlib model training is not idiomatic in DLT pipelines")
            return [
                "# NeuralNetwork: MLlib training is not idiomatic in DLT.",
                f"# Target: {node.target_field}, Features: {node.feature_fields!r}, layers={node.hidden_layers}",
                f"return {inp}  # passthrough - train model outside DLT",
            ], warnings

        if isinstance(node, GammaRegressionNode):
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"GammaRegression (node {node.node_id}): MLlib model training is not idiomatic in DLT pipelines")
            return [
                "# GammaRegression (GLM gamma): MLlib training is not idiomatic in DLT.",
                f"# Target: {node.target_field}, Features: {node.feature_fields!r}, link={node.link_function}",
                f"return {inp}  # passthrough - train model outside DLT",
            ], warnings

        if isinstance(node, CountRegressionNode):
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"CountRegression (node {node.node_id}): MLlib model training is not idiomatic in DLT pipelines")
            return [
                "# CountRegression (GLM poisson): MLlib training is not idiomatic in DLT.",
                f"# Target: {node.target_field}, Features: {node.feature_fields!r}, link={node.link_function}",
                f"return {inp}  # passthrough - train model outside DLT",
            ], warnings

        if isinstance(node, SplineModelNode):
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"SplineModel (node {node.node_id}): no MLlib equivalent; not idiomatic in DLT")
            return [
                "# SplineModel: no direct Spark MLlib equivalent.",
                f"# Target: {node.target_field}, max_knots={node.max_knots}",
                f"return {inp}  # passthrough - implement outside DLT",
            ], warnings

        if isinstance(node, StepwiseNode):
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"Stepwise (node {node.node_id}): feature selection is not idiomatic in DLT pipelines")
            return [
                "# Stepwise feature selection: not idiomatic in DLT.",
                f"# Target: {node.target_field}, Features: {node.feature_fields!r}, direction={node.direction}",
                f"return {inp}  # passthrough - run feature selection outside DLT",
            ], warnings

        if isinstance(node, KCentroidsNode):
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"KCentroids (node {node.node_id}): MLlib clustering is not idiomatic in DLT pipelines")
            return [
                "# KMeans clustering: not idiomatic in DLT.",
                f"# Features: {node.feature_fields!r}, k={node.k}",
                f"return {inp}  # passthrough - train model outside DLT",
            ], warnings

        if isinstance(node, PrincipalComponentsNode):
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"PCA (node {node.node_id}): MLlib PCA is not idiomatic in DLT pipelines")
            return [
                "# PCA: not idiomatic in DLT.",
                f"# Features: {node.feature_fields!r}, num_components={node.num_components}",
                f"return {inp}  # passthrough - run PCA outside DLT",
            ], warnings

        if isinstance(node, CrossValidationNode):
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"CrossValidation (node {node.node_id}): not idiomatic in DLT pipelines")
            return [
                "# CrossValidation: not idiomatic in DLT.",
                f"# num_folds={node.num_folds}, model={node.model_reference}",
                f"return {inp}  # passthrough - run CV outside DLT",
            ], warnings

        if isinstance(node, ARIMANode):
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"ARIMA (node {node.node_id}): time series models are not idiomatic in DLT pipelines")
            return [
                f"# ARIMA({node.p},{node.d},{node.q}): not idiomatic in DLT.",
                f"# time={node.time_field}, value={node.value_field}",
                f"return {inp}  # passthrough - use Prophet or statsmodels outside DLT",
            ], warnings

        if isinstance(node, ETSNode):
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"ETS (node {node.node_id}): time series models are not idiomatic in DLT pipelines")
            return [
                "# ETS: not idiomatic in DLT.",
                f"# time={node.time_field}, value={node.value_field}",
                f"return {inp}  # passthrough - use Prophet or statsmodels outside DLT",
            ], warnings

        if isinstance(node, AppendClusterNode):
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"AppendCluster (node {node.node_id}): clustering models are not idiomatic in DLT pipelines")
            return [
                "# AppendCluster: not idiomatic in DLT.",
                f"return {inp}  # passthrough - apply clustering outside DLT",
            ], warnings

        if isinstance(node, FindNearestNeighborsNode):
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"FindNearestNeighbors (node {node.node_id}): KNN is not idiomatic in DLT pipelines")
            return [
                "# FindNearestNeighbors: not idiomatic in DLT.",
                f"return {inp}  # passthrough - run KNN outside DLT",
            ], warnings

        if isinstance(node, KCentroidsDiagnosticsNode):
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"KCentroidsDiagnostics (node {node.node_id}): cluster diagnostics are not idiomatic in DLT pipelines")
            return [
                "# KCentroidsDiagnostics: not idiomatic in DLT.",
                f"return {inp}  # passthrough - run diagnostics outside DLT",
            ], warnings

        if isinstance(node, LiftChartNode):
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"LiftChart (node {node.node_id}): model evaluation is not idiomatic in DLT pipelines")
            return [
                "# LiftChart: not idiomatic in DLT.",
                f"return {inp}  # passthrough - compute lift chart outside DLT",
            ], warnings

        if isinstance(node, ModelComparisonNode):
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"ModelComparison (node {node.node_id}): model comparison is not idiomatic in DLT pipelines")
            return [
                "# ModelComparison: not idiomatic in DLT.",
                f"return {inp}  # passthrough - use MLflow for model comparison",
            ], warnings

        if isinstance(node, ModelCoefficientsNode):
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"ModelCoefficients (node {node.node_id}): coefficient extraction is not idiomatic in DLT pipelines")
            return [
                "# ModelCoefficients: not idiomatic in DLT.",
                f"return {inp}  # passthrough - extract coefficients outside DLT",
            ], warnings

        if isinstance(node, TSForecastNode):
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"TSForecast (node {node.node_id}): time series forecasting is not idiomatic in DLT pipelines")
            return [
                "# TSForecast: not idiomatic in DLT.",
                f"return {inp}  # passthrough - use Prophet outside DLT",
            ], warnings

        if isinstance(node, MeansTestNode):
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"TestOfMeans (node {node.node_id}): statistical tests are not idiomatic in DLT pipelines")
            return [
                "# TestOfMeans: not idiomatic in DLT.",
                f"return {inp}  # passthrough - run t-tests outside DLT",
            ], warnings

        if isinstance(node, VarianceInflationFactorsNode):
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"VIF (node {node.node_id}): VIF analysis is not idiomatic in DLT pipelines")
            return [
                "# VarianceInflationFactors: not idiomatic in DLT.",
                f"return {inp}  # passthrough - run VIF outside DLT",
            ], warnings

        if isinstance(node, ABAnalysisNode):
            inp = self._get_single_input_read(input_tables)
            warnings.append(f"ABAnalysis (node {node.node_id}): A/B analysis is not idiomatic in DLT pipelines")
            return [
                "# ABAnalysis: not idiomatic in DLT.",
                f"return {inp}  # passthrough - run A/B analysis outside DLT",
            ], warnings

        if isinstance(node, UnsupportedNode):
            inp = self._get_single_input_read(input_tables)
            reason = node.unsupported_reason or "No auto-conversion"
            warnings.append(f"Unsupported node {node.node_id}: {reason}")
            return [
                f"# UNSUPPORTED: {node.original_tool_type} - {reason}",
                f"return {inp}  # passthrough placeholder",
            ], warnings

        # Fallback
        inp = self._get_single_input_read(input_tables)
        warnings.append(f"No DLT generator for {type(node).__name__} (node {node.node_id})")
        return [
            f"# TODO: {type(node).__name__} needs manual conversion",
            f"return {inp}",
        ], warnings

    def _body_ReadNode(self, node: ReadNode) -> list[str]:
        fmt = self._map_file_format(node.file_format)
        if node.source_type == "database" and node.table_name:
            return [f'return spark.table("{node.table_name}")']
        if node.source_type == "database" and node.query:
            return [f'return spark.sql("""{node.query}""")']
        path = node.file_path or "UNKNOWN_PATH"
        options = ""
        if fmt == "csv":
            opts = ['"header", "true"'] if node.has_header else ['"header", "false"']
            if node.delimiter and node.delimiter != ",":
                opts.append(f'"delimiter", "{node.delimiter}"')
            options = "".join(f".option({o})" for o in opts)
        return [f'return spark.read.format("{fmt}"){options}.load("{path}")']

    # _map_file_format inherited from CodeGenerator base class
