"""Unity Catalog DDL generator — CREATE TABLE / EXTERNAL TABLE statements.

Walks ReadNode/WriteNode in the DAG and generates DDL for Unity Catalog,
resolving connections via the connection mapping configuration.
"""

from __future__ import annotations

import logging
from pathlib import Path

from a2d.config import ConversionConfig
from a2d.connections import ConnectionMappingConfig, load_connection_mapping
from a2d.generators.base import GeneratedFile
from a2d.ir.graph import WorkflowDAG
from a2d.ir.nodes import (
    CloudStorageNode,
    DynamicInputNode,
    ReadNode,
    WriteNode,
)

logger = logging.getLogger("a2d.generators.unity_catalog")

# Map Alteryx file formats to Delta/external table formats
_DDL_FORMAT_MAP = {
    "csv": "CSV",
    "parquet": "PARQUET",
    "json": "JSON",
    "avro": "AVRO",
    "xlsx": "CSV",  # best approximation
    "yxdb": "PARQUET",  # best approximation
    "": "DELTA",
}

# read_files() format keywords for non-Delta formats. read_files is the modern,
# UC Volumes-friendly replacement for legacy CREATE EXTERNAL TABLE … USING <fmt>.
# See: https://docs.databricks.com/aws/en/sql/language-manual/functions/read_files.html
_READ_FILES_FORMAT = {
    "CSV": "csv",
    "PARQUET": "parquet",
    "JSON": "json",
    "AVRO": "avro",
}


class UnityCatalogGenerator:
    """Generate DDL statements for Unity Catalog tables."""

    def __init__(self, config: ConversionConfig) -> None:
        self.config = config
        self._mapping = self._load_mapping()

    def _load_mapping(self) -> ConnectionMappingConfig:
        """Load connection mapping from config path, or create default."""
        if self.config.connection_mapping_path:
            return load_connection_mapping(self.config.connection_mapping_path)
        return ConnectionMappingConfig(
            default_catalog=self.config.catalog_name,
            default_schema=self.config.schema_name,
        )

    def generate_ddl(self, dag: WorkflowDAG) -> list[GeneratedFile]:
        """Generate DDL files for all IO nodes in the DAG."""
        statements: list[str] = []

        for node in dag.topological_sort():
            if isinstance(node, ReadNode):
                stmt = self._read_node_ddl(node)
                if stmt:
                    statements.append(stmt)
            elif isinstance(node, WriteNode):
                stmt = self._write_node_ddl(node)
                if stmt:
                    statements.append(stmt)
            elif isinstance(node, CloudStorageNode | DynamicInputNode):
                stmt = self._external_node_ddl(node)
                if stmt:
                    statements.append(stmt)

        if not statements:
            return []

        content = "-- Unity Catalog DDL generated by a2d\n"
        content += "-- Review and customize before executing\n\n"
        content += "\n\n".join(statements) + "\n"

        return [
            GeneratedFile(
                filename="unity_catalog_ddl.sql",
                content=content,
                file_type="sql",
            )
        ]

    def _read_node_ddl(self, node: ReadNode) -> str | None:
        """Generate DDL for a ReadNode."""
        if node.source_type == "database" or node.connection_string:
            # Database source — resolve via connection mapping
            conn_name = node.connection_string or "default"
            table_name = node.table_name or f"table_{node.node_id}"
            fq_name = self._mapping.resolve(conn_name, table_name)

            return (
                f"CREATE TABLE IF NOT EXISTS {fq_name} (\n"
                f"  -- Schema to be defined based on source data\n"
                f"  -- Source: {conn_name}\n"
                f");"
            )
        elif node.file_path:
            # File source — external table
            table_name = self._table_name_from_path(node.file_path, node.node_id)
            fq_name = self._mapping.resolve("", table_name)
            fmt = _DDL_FORMAT_MAP.get(node.file_format.lower(), "DELTA")

            if fmt == "DELTA":
                return (
                    f"CREATE TABLE IF NOT EXISTS {fq_name}\n  -- Migrated from file: {node.file_path}\n  USING DELTA\n;"
                )
            else:
                # Modern pattern: ingest non-Delta files via read_files() into a
                # managed Delta table. UC Volumes friendly, governed, and avoids
                # the legacy CREATE EXTERNAL TABLE USING <fmt> syntax.
                # Docs: https://docs.databricks.com/aws/en/sql/language-manual/functions/read_files.html
                rf_fmt = _READ_FILES_FORMAT.get(fmt, fmt.lower())
                return (
                    f"CREATE TABLE IF NOT EXISTS {fq_name}\n"
                    f"  USING DELTA\n"
                    f"  AS SELECT * FROM read_files(\n"
                    f"    '{node.file_path}',\n"
                    f"    format => '{rf_fmt}'\n"
                    f"  )\n"
                    f"  -- Original file: {node.file_path}\n;"
                )
        return None

    def _write_node_ddl(self, node: WriteNode) -> str | None:
        """Generate DDL for a WriteNode."""
        conn_name = node.connection_string or "default"
        table_name = node.table_name or self._table_name_from_path(node.file_path, node.node_id)
        fq_name = self._mapping.resolve(conn_name, table_name)

        return (
            f"CREATE TABLE IF NOT EXISTS {fq_name} (\n"
            f"  -- Schema to be defined based on output data\n"
            f"  -- Destination: {node.file_path or node.connection_string}\n"
            f"  -- Write mode: {node.write_mode}\n"
            f") USING DELTA;"
        )

    def _external_node_ddl(self, node) -> str | None:
        """Generate DDL for CloudStorageNode or DynamicInputNode."""
        if isinstance(node, CloudStorageNode):
            path = node.path or f"node_{node.node_id}"
            table_name = self._table_name_from_path(path, node.node_id)
            fq_name = self._mapping.resolve("", table_name)
            fmt = _DDL_FORMAT_MAP.get(node.file_format.lower(), "DELTA")
            location = f"{node.bucket_or_container}/{path}"

            if fmt == "DELTA":
                # Already-Delta external data: keep the EXTERNAL TABLE form so the
                # table points at the existing location.
                return (
                    f"CREATE TABLE IF NOT EXISTS {fq_name}\n"
                    f"  USING DELTA\n"
                    f"  LOCATION '{location}'\n"
                    f"  -- Provider: {node.provider};"
                )
            # Non-Delta: ingest via read_files() (UC Volumes-friendly modern pattern).
            rf_fmt = _READ_FILES_FORMAT.get(fmt, fmt.lower())
            return (
                f"CREATE TABLE IF NOT EXISTS {fq_name}\n"
                f"  USING DELTA\n"
                f"  AS SELECT * FROM read_files(\n"
                f"    '{location}',\n"
                f"    format => '{rf_fmt}'\n"
                f"  )\n"
                f"  -- Provider: {node.provider};"
            )
        elif isinstance(node, DynamicInputNode):
            table_name = f"dynamic_input_{node.node_id}"
            fq_name = self._mapping.resolve("", table_name)

            return (
                f"CREATE TABLE IF NOT EXISTS {fq_name}\n"
                f"  -- Dynamic input from: {node.file_path_pattern or node.template_query}\n"
                f"  USING DELTA;"
            )
        return None

    @staticmethod
    def _table_name_from_path(file_path: str, node_id: int) -> str:
        """Derive a table name from a file path."""
        if not file_path:
            return f"table_{node_id}"
        stem = Path(file_path).stem
        # Sanitize to valid identifier
        clean = "".join(c if c.isalnum() or c == "_" else "_" for c in stem).strip("_")
        return clean or f"table_{node_id}"
