"""Databricks Workflow JSON generator.

Produces a JSON job definition that can be imported into Databricks
via the Jobs API or Terraform.

Cloud portability
-----------------
The auto-generated ``job_clusters`` entry has its ``node_type_id`` selected
from :data:`a2d.config.CLOUD_NODE_TYPE_IDS` based on
``ConversionConfig.cloud`` (default: ``"aws"`` -> ``i3.xlarge``). This avoids
the older Azure-only ``Standard_DS3_v2`` default that produced runtime errors
on AWS / GCP workspaces. Override via the CLI flag ``--cloud {aws|azure|gcp}``.

Modern Jobs API alignment
-------------------------
* ``"format": "MULTI_TASK"`` (vestigial since Jobs API 2.1) is omitted.
* A top-level ``queue: {enabled: true}`` is emitted for run-queue concurrency
  control (Databricks' recommended default for multi-task jobs).
* A top-level ``parameters: []`` placeholder is emitted so users have a
  documented spot to add job-level parameters.
* ``run_as`` and ``webhook_notifications`` are intentionally NOT auto-populated
  — they encode permission / on-call decisions that should be made by the
  operator. We surface comments in the generated file pointing at where to add
  them.
* The single auto-generated cluster is exposed via ``job_clusters[]`` with key
  ``"main"`` and each task references it through ``job_cluster_key: "main"``,
  matching Databricks best practice and aligning with the DAB generator.
"""

from __future__ import annotations

import json
import logging

from a2d.config import OutputFormat
from a2d.generators.base import CodeGenerator, GeneratedFile, GeneratedOutput
from a2d.ir.graph import WorkflowDAG

logger = logging.getLogger("a2d.generators.workflow_json")


# Shared key for the single auto-provisioned job cluster. Tasks reference
# this via ``job_cluster_key`` so callers can swap the cluster spec in one
# place (matches the DAB generator's convention).
_DEFAULT_JOB_CLUSTER_KEY = "main"

# Operator notes about fields we intentionally do NOT auto-populate. These
# go into a sibling ``*_workflow.README.md`` so the JSON file itself stays
# strict (valid for ``json.loads``, jq, third-party tooling) while humans
# still get the context. Don't put comments in the JSON.
_OPERATOR_NOTES = (
    "# {workflow_name} — operator notes\n"
    "\n"
    "Generated by a2d. The companion ``{workflow_name}_workflow.json`` is\n"
    "valid JSON — review the items below before deploying.\n"
    "\n"
    "## Intentionally omitted fields\n"
    "\n"
    "- ``run_as`` — the job runs as the deploying principal by default. Add\n"
    '  ``"run_as": {{"user_name": "..."}}`` or ``{{"service_principal_name": "..."}}``\n'
    "  to the JSON if you want a specific identity.\n"
    "- ``webhook_notifications`` — only ``email_notifications`` is wired up.\n"
    "  Add a ``webhook_notifications`` block alongside it for Slack/PagerDuty.\n"
)


class WorkflowJsonGenerator(CodeGenerator):
    """Generate Databricks Workflow job definition JSON."""

    def generate(self, dag: WorkflowDAG, workflow_name: str = "workflow") -> GeneratedOutput:
        warnings: list[str] = []

        # Determine notebook path based on output format
        if self.config.output_format == OutputFormat.DLT:
            notebook_path = f"/Workspace/Shared/a2d/{workflow_name}_dlt"
            task = self._build_dlt_task(workflow_name, notebook_path)
        elif self.config.output_format == OutputFormat.LAKEFLOW:
            notebook_path = f"/Workspace/Shared/a2d/{workflow_name}_lakeflow.sql"
            task = self._build_sql_task(workflow_name, notebook_path)
        else:
            notebook_path = f"/Workspace/Shared/a2d/{workflow_name}"
            task = self._build_notebook_task(workflow_name, notebook_path)

        # Cloud-aware node_type_id (driven by ConversionConfig.cloud).
        node_type_id = self.config.node_type_id

        job_definition = {
            "name": f"a2d_{workflow_name}",
            "description": f"Migrated from Alteryx workflow: {workflow_name}.yxmd",
            "tags": {
                "source": "alteryx",
                "migrated_by": "a2d",
                "original_workflow": f"{workflow_name}.yxmd",
            },
            "tasks": [task],
            "job_clusters": [
                {
                    "job_cluster_key": _DEFAULT_JOB_CLUSTER_KEY,
                    "new_cluster": {
                        "spark_version": f"{self.config.dbr_version}.x-scala2.12",
                        "num_workers": 2,
                        # Cloud-specific worker SKU — see a2d.config.CLOUD_NODE_TYPE_IDS.
                        "node_type_id": node_type_id,
                        "spark_conf": {
                            "spark.databricks.delta.preview.enabled": "true",
                        },
                    },
                }
            ],
            # Concurrency control. Recommended default per the Jobs API 2.2
            # docs — without it, queued runs are dropped instead of held.
            "queue": {"enabled": True},
            # Placeholder for job-level parameters. Empty by default; users
            # can add `{ "name": "...", "default": "..." }` entries here.
            "parameters": [],
            "max_concurrent_runs": 1,
        }

        # Strict JSON — operator notes go into the sibling README so any
        # downstream consumer (jq, json.loads, CI linting) can parse this
        # file directly without stripping anything.
        content = json.dumps(job_definition, indent=2) + "\n"
        notes = _OPERATOR_NOTES.format(workflow_name=workflow_name)

        files = [
            GeneratedFile(
                filename=f"{workflow_name}_workflow.json",
                content=content,
                file_type="json",
            ),
            GeneratedFile(
                filename=f"{workflow_name}_workflow.README.md",
                content=notes,
                file_type="markdown",
            ),
        ]

        stats = {
            "total_tasks": 1,
            "notebook_path": notebook_path,
            "cloud": self.config.cloud,
            "node_type_id": node_type_id,
        }

        return GeneratedOutput(files=files, warnings=warnings, stats=stats)

    @staticmethod
    def _build_notebook_task(workflow_name: str, notebook_path: str) -> dict:
        return {
            "task_key": f"{workflow_name}_main",
            "description": f"Run migrated workflow: {workflow_name}",
            "job_cluster_key": _DEFAULT_JOB_CLUSTER_KEY,
            "notebook_task": {
                "notebook_path": notebook_path,
                "source": "WORKSPACE",
            },
            "timeout_seconds": 3600,
            "max_retries": 0,
        }

    @staticmethod
    def _build_sql_task(workflow_name: str, sql_path: str) -> dict:
        return {
            "task_key": f"{workflow_name}_lakeflow",
            "description": f"Run Lakeflow SQL: {workflow_name}",
            "job_cluster_key": _DEFAULT_JOB_CLUSTER_KEY,
            "sql_task": {
                "file": {"path": sql_path},
                "warehouse_id": "PLACEHOLDER_WAREHOUSE_ID",
            },
            "timeout_seconds": 3600,
            "max_retries": 0,
        }

    @staticmethod
    def _build_dlt_task(workflow_name: str, notebook_path: str) -> dict:
        return {
            "task_key": f"{workflow_name}_dlt_pipeline",
            "description": f"Run DLT pipeline: {workflow_name}",
            "pipeline_task": {
                "pipeline_id": "PLACEHOLDER_PIPELINE_ID",
                "full_refresh": False,
            },
            "timeout_seconds": 3600,
            "max_retries": 0,
        }
